name: Run CI
on: [push, pull_request]

jobs:
  normal_ci:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' }}
    steps:

      - name: setp 1
        run: echo ${{ github.event_name }}

      - name: step 2
        run: echo ${{ github.retention_days }}
