name: Run CI
on: [push, pull_request]

jobs:
  normal_ci:
    runs-on: ubuntu-latest

    # if: ${{ github.event_name == 'pull_request' }}
    steps:

      - name: Run normal CI
        run: echo ${{ github.event_name }}

      - name: Run normal CI
        run: echo ${{ github.retention_days }}
